export const navLinkData = [
    {
        path: { name: "dashboard" },
        title: "Dashboard",
        value: "dashboard",
        icon: "mdi-view-dashboard-outline",
        iconSelect: "mdi-view-dashboard",
    },
    {
        path: { name: "employee" },
        title: "Employees",
        value: "employees",
        icon: "mdi-account-group-outline",
        iconSelect: "mdi-account-group",
    },
    {
        path: { name: "employeeViolation" },
        title: "Employee Violations",
        value: "employeeViolations",
        icon: "mdi-account-alert-outline",
        iconSelect: "mdi-account-alert",
    },
    {
        path: { name: "pendingViolation" },
        title: "Pending Violations",
        value: "pendingViolations",
        icon: "mdi-account-clock-outline",
        iconSelect: "mdi-account-clock",
    },
    {
        path: { name: "violation" },
        title: "Violations",
        value: "violation",
        icon: "mdi-alert-octagon-outline",
        iconSelect: "mdi-alert-octagon",
    },
    {
        path: { name: "disciplinaryMeasure" },
        title: "Disciplinary Measures",
        value: "disciplinaryMeasures",
        icon: "mdi-shield-outline",
        iconSelect: "mdi-shield",
    },
    {
        path: { name: "contract" },
        title: "Contracts",
        value: "contract",
        icon: "mdi-file-edit-outline",
        iconSelect: "mdi-file-edit",
    },
];
